-- Boozt.iq initial schema (Postgres / Supabase)
-- Run in Supabase SQL Editor or: supabase db push (after linking project)
--
-- Idempotent: safe to re-run if objects already exist (e.g. pasting whole file twice).

create extension if not exists "pgcrypto";

-- ─── Categories & subcategories (fixed UUIDs — see lib/supabase/catalog-ids.ts) ───

create table if not exists public.categories (
  id uuid primary key,
  slug text not null unique,
  name_en text not null,
  name_ar text not null,
  icon text not null default '📦',
  sort_order int not null default 0,
  product_count int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.subcategories (
  id uuid primary key,
  category_id uuid not null references public.categories (id) on delete cascade,
  slug text not null,
  name_en text not null,
  name_ar text not null,
  sort_order int not null default 0,
  unique (category_id, slug)
);

-- ─── Products (CSV + storefront; id can be set from import) ───

create table if not exists public.products (
  id integer generated by default as identity primary key,
  product_name text not null,
  category text,
  weight text,
  price text,
  image text
);

-- ─── Orders ───

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid (),
  customer_name text not null,
  customer_phone text not null,
  area text not null,
  notes text not null default '',
  items jsonb not null,
  total numeric not null,
  status text not null default 'pending',
  pdf_url text,
  pdf_path text,
  pdf_generated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ─── Reviews ───

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid (),
  product_id text not null,
  reviewer_name text not null,
  rating int not null,
  comment text not null,
  locale text not null default 'en',
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists reviews_product_id_idx on public.reviews (product_id);
create index if not exists reviews_approved_idx on public.reviews (approved);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- ─── Seed categories (same tree as former Firestore seed) ───

insert into public.categories (id, slug, name_en, name_ar, icon, sort_order, product_count)
values
  ('a0000001-0000-4000-8000-000000000001', 'hookah', 'Hookah', 'شيشة', '🪔', 1, 0),
  ('a0000001-0000-4000-8000-000000000002', 'vape', 'Vape', 'فيب', '💨', 2, 0),
  ('a0000001-0000-4000-8000-000000000003', 'pods', 'Disposable Pods', 'بودات يوز وارمي', '🔋', 3, 0),
  ('a0000001-0000-4000-8000-000000000004', 'boardgames', 'Board Games', 'ألعاب لوحية', '🎲', 4, 0)
on conflict (id) do nothing;

insert into public.subcategories (id, category_id, slug, name_en, name_ar, sort_order)
values
  ('b0000001-0000-4000-8000-000001000001', 'a0000001-0000-4000-8000-000000000001', 'molasses', 'Molasses & Flavors', 'معسل ونكهات', 1),
  ('b0000001-0000-4000-8000-000001000006', 'a0000001-0000-4000-8000-000000000001', 'parts', 'Hookah Parts', 'قطع الشيشة', 2),
  ('b0000001-0000-4000-8000-000002000001', 'a0000001-0000-4000-8000-000000000002', 'devices', 'Devices & Mods', 'أجهزة وموديلات', 1),
  ('b0000001-0000-4000-8000-000002000002', 'a0000001-0000-4000-8000-000000000002', 'eliquids', 'E-Liquids & Juices', 'سوائل إلكترونية', 2),
  ('b0000001-0000-4000-8000-000002000003', 'a0000001-0000-4000-8000-000000000002', 'coils', 'Coils & Tanks', 'ملفات وخزانات', 3),
  ('b0000001-0000-4000-8000-000002000004', 'a0000001-0000-4000-8000-000000000002', 'batteries', 'Batteries & Chargers', 'بطاريات وشاحنات', 4),
  ('b0000001-0000-4000-8000-000002000005', 'a0000001-0000-4000-8000-000000000002', 'oxbar', 'Oxbar', 'أوكسبار', 5),
  ('b0000001-0000-4000-8000-000002000006', 'a0000001-0000-4000-8000-000000000002', 'oxbar-g-turbo', 'Oxbar G Turbo', 'أوكسبار جي تيربو', 6),
  ('b0000001-0000-4000-8000-000003000005', 'a0000001-0000-4000-8000-000000000003', 'vozol', 'Vozol', 'فوزول', 1),
  ('b0000001-0000-4000-8000-000003000006', 'a0000001-0000-4000-8000-000000000003', 'oxbar-pod', 'Oxbar Pod', 'أوكسبار بود', 2),
  ('b0000001-0000-4000-8000-000004000001', 'a0000001-0000-4000-8000-000000000004', 'strategy', 'Strategy', 'ألعاب استراتيجية', 1),
  ('b0000001-0000-4000-8000-000004000002', 'a0000001-0000-4000-8000-000000000004', 'party', 'Party & Family', 'عائلية وحفلات', 2),
  ('b0000001-0000-4000-8000-000004000003', 'a0000001-0000-4000-8000-000000000004', 'cards', 'Card Games', 'ألعاب ورق', 3),
  ('b0000001-0000-4000-8000-000004000004', 'a0000001-0000-4000-8000-000000000004', 'puzzles', 'Puzzles', 'بازل', 4)
on conflict (id) do nothing;

-- ─── RLS: public read for catalog; writes via service role only ───

alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "categories_select_public" on public.categories;
create policy "categories_select_public" on public.categories for select using (true);

drop policy if exists "subcategories_select_public" on public.subcategories;
create policy "subcategories_select_public" on public.subcategories for select using (true);

drop policy if exists "products_select_public" on public.products;
create policy "products_select_public" on public.products for select using (true);

drop policy if exists "reviews_select_public" on public.reviews;
create policy "reviews_select_public" on public.reviews for select using (true);

-- Service role bypasses RLS — no insert/update policies needed for server-side admin.

-- ─── Storage bucket for order PDF reports ───
insert into storage.buckets (id, name, public)
values ('order-reports', 'order-reports', true)
on conflict (id) do nothing;
