-- One-time catalog rows: Taha Cadillac Hookah + molasses / charcoal packets.
-- Columns: product_name, category, weight (grams / pack note), price (IQD as text), image URL.
--
-- Weight assumptions (edit rows in Supabase if your SKUs differ):
--   ~50 g  — single flavor pouches (typical small retail packet)
--   ~250 g — products with "Box" in the name (common Al Fakher / Mazaya box size)
--   ~500 g — Mas Two Apples bulk-style listing; Escape charcoal bag (approx.)
--   Hookah — no pack weight (null)

insert into public.products (product_name, category, weight, price, image)
values
  ('Taha Cadillac Hookah', 'Hookah', null, '185000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8582.jpg'),
  ('JBR Strawberry Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8595.PNG'),
  ('JBR Tiramisu Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8604.PNG'),
  ('JBR Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8596.PNG'),
  ('JBR Ice Cream Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8597.PNG'),
  ('JBR English Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8598.PNG'),
  ('JBR Melon & Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8599.PNG'),
  ('JBR Deja Vu Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8601.PNG'),
  ('JBR Mint & Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8602.PNG'),
  ('JBR Melon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8600.PNG'),
  ('Al Fakher Peach Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8617.PNG'),
  ('Al Fakher Chocolate Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8618.PNG'),
  ('Al Fakher Two Apples Molasses Box', 'Hookah Molasses Packets', '250 g', '28000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8607.PNG'),
  ('Al Fakher Vanilla Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8608.PNG'),
  ('Al Fakher Watermelon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8619.PNG'),
  ('Al Fakher Melon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8620.PNG'),
  ('Mazaya Mistaka Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8621.PNG'),
  ('Mazaya Gum & Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8655.png'),
  ('Mazaya Lemon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8632.PNG'),
  ('Mazaya Ruby Crush Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8622.PNG'),
  ('Mazaya Orange With Cream Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8623.PNG'),
  ('Mazaya English Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8624.PNG'),
  ('Mazaya Double Apple Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8625.PNG'),
  ('Mazaya Kiwi & Lemon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8626.PNG'),
  ('Mazaya Four Seasons Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8627.PNG'),
  ('Mazaya Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8628.PNG'),
  ('Mazaya Gum & Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8629.PNG'),
  ('Mazaya Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8630.PNG'),
  ('Mazaya Black Grape Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8631.PNG'),
  ('Al Fakher Grape Molasses Box', 'Hookah Molasses Packets', '250 g', '28000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8609.PNG'),
  ('Mazaya Lemon & Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8632.PNG'),
  ('Nakhla Double Apple Molasses', 'Hookah Molasses Packets', '50 g', '3000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8634.PNG'),
  ('Sharbatli Lemon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8634.PNG'),
  ('Sharbatli Mix Lemon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8635.PNG'),
  ('Sharbatli Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8636.PNG'),
  ('Sharbatli Lebanese Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8656.png'),
  ('Sharbatli Mint & Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8636.PNG'),
  ('Al Fakhama Lemon & Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8637.PNG'),
  ('Al Fakhama Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8638.PNG'),
  ('Al Fakhama Gum & Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8639.PNG'),
  ('Al Fakhama Bounty Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8640.PNG'),
  ('Al Fakher Gum  Mint Molasses Box', 'Hookah Molasses Packets', '250 g', '7500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8643.PNG'),
  ('Al Fakher Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8610.PNG'),
  ('Adalya Moscow Nights Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8645.PNG'),
  ('Adalya Havana Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8647.PNG'),
  ('Adalya Lady Killer Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8642.PNG'),
  ('Adalya Shahryar Killer Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8644.PNG'),
  ('Adalya Live 66 Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8646.PNG'),
  ('Adalya Gum & Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8648.PNG'),
  ('Adalya English Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8641.PNG'),
  ('Al Fakher Mint & Gum Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8611.PNG'),
  ('Mas Two Apples Molasses', 'Hookah Molasses Packets', '500 g', '16000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8603.PNG'),
  ('Escape Coconut Charcoal', 'Hookah Molasses Packets', '500 g', '2000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8612.PNG'),
  ('Al Fakher Double Apple Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8613.PNG'),
  ('Al Fakher Orange Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8614.PNG'),
  ('Al Fakher Coconut Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8615.PNG'),
  ('Al Fakher Mint & Lemon Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8616.PNG'),
  ('Al Amasi Mint Ice Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8649.PNG'),
  ('Al Amasi Gum & Mint Ice Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8650.PNG'),
  ('Al Amasi Lemon & Mint Ice Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8651.PNG'),
  ('Mazaya Gum & Mint Molasses Box', 'Hookah Molasses Packets', '250 g', '6500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8652.PNG'),
  ('Al Fakher Mint Molasses Box', 'Hookah Molasses Packets', '250 g', '7500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8653.PNG'),
  ('Al Fakher Mint Molasses', 'Hookah Molasses Packets', '50 g', '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8606.PNG'),
  ('Al Fakher Gum Mint Molasses Box', 'Hookah Molasses Packets', '250 g', '7500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8605.PNG'),
  ('Al Fakher Double Apple Molasses Box', 'Hookah Molasses Packets', '250 g', '7500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8654.PNG');
