-- Hookah Parts accessories (category text matches inferCategorySlugs → hookah / parts).
-- price = IQD as text; weight null (not sold by gram).

insert into public.products (product_name, category, weight, price, image)
values
  ('Najah Al Marzouk Hookah Tray Blue', 'Hookah Parts', null, '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8670.PNG'),
  ('Ceramic Hookah Bowl', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8671.PNG'),
  ('Disposable Hookah Hose', 'Hookah Parts', null, '2500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8672.PNG'),
  ('Richman Hookah Hose', 'Hookah Parts', null, '6000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8673.PNG'),
  ('Colored Hookah Hose', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8674.PNG'),
  ('White Hookah Vase', 'Hookah Parts', null, '4000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8675.PNG'),
  ('Pottery Bowl 1', 'Hookah Parts', null, '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8682.PNG'),
  ('Anime Hookah Bowl', 'Hookah Parts', null, '10000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8683.PNG'),
  ('Pottery Bowl 2', 'Hookah Parts', null, '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8684.PNG'),
  ('Anime Hookah Bowl', 'Hookah Parts', null, '10000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8685.PNG'),
  ('Disposal Hose', 'Hookah Parts', null, '1250', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8686.PNG'),
  ('Hookah Bowl 1', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8687.PNG'),
  ('Hookah Bowl 2', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8688.PNG'),
  ('Hookah Bowl 3', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8689.PNG'),
  ('Hookah Bowl 6', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8690.PNG'),
  ('Hookah Bowl 8', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8691.PNG'),
  ('Hookah Bowl 9', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8692.PNG'),
  ('Hookah Bowl 10', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8693.PNG'),
  ('Hookah Bowl 11', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8694.PNG'),
  ('Hookah Bowl 12', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8695.PNG'),
  ('Hookah Bowl 13', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8696.PNG'),
  ('Hookah Bowl 14', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8697.PNG'),
  ('Hookah Bowl 15', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8698.PNG'),
  ('Hookah Bowl 16', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8699.PNG'),
  ('Hookah Bowl 17', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8700.PNG'),
  ('Hookah Bowl 18', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8701.PNG'),
  ('Hookah Bowl 19', 'Hookah Parts', null, '5500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8702.PNG'),
  ('Taha Hookah Hose', 'Hookah Parts', null, '28000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8703.PNG'),
  ('Cloud Bowl', 'Hookah Parts', null, '13000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8704.PNG'),
  ('Taalaka Hookah Mouth', 'Hookah Parts', null, '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8705.PNG'),
  ('Hookah Mouth Bag', 'Hookah Parts', null, '1000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8706.PNG'),
  ('Babylon Hookah Vase 2', 'Hookah Parts', null, '6000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8707.PNG'),
  ('Babylon Hookah Vase 3', 'Hookah Parts', null, '6000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8708.PNG'),
  ('Green Hookah Vase', 'Hookah Parts', null, '4000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8676.PNG'),
  ('Blue Hookah Vase', 'Hookah Parts', null, '4000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8677.PNG'),
  ('Babylon Hookah Shisha', 'Hookah Parts', null, '8000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8678.PNG'),
  ('Basmah Pottery Bowl', 'Hookah Parts', null, '1500', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8679.PNG'),
  ('Taha Mandela Hookah Shisha', 'Hookah Parts', null, '11000', 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8680.PNG');
('Hole Puncher', 'Hookah Parts', null, 1500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8772.png'),
('Mercedes Style Hookah Bowl Buckle', 'Hookah Parts', null, 2000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8743.PNG'),
('Hookah Bowl Grommet', 'Hookah Parts', null, 500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8744.PNG'),
('Hookah Grommet', 'Hookah Parts', null, 750, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8745.PNG'),
('Hookah Hose Grommet', 'Hookah Parts', null, 500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8746.PNG'),
('Hookah Diffuser', 'Hookah Parts', null, 2000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8747.PNG'),
('Ice Bottle 2', 'Hookah Parts', null, 1750, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8760.PNG'),
('Bowl Punching Box', 'Hookah Parts', null, 1500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8761.PNG'),
('Nawras Hookah Aluminum', 'Hookah Parts', null, 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8762.PNG'),
('Al Raqi Hookah Aluminum', 'Hookah Parts', null, 1500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8763.PNG'),
('Laten Argeeleh Wash', 'Hookah Parts', null, 6500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8764.PNG'),
('Punching Needle', 'Hookah Parts', null, 500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8765.PNG'),
('Punching Needle With Wooden Handle', 'Hookah Parts', null, 1000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8766.PNG'),
('Large Aluminum Roll', 'Hookah Parts', null, 17500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8767.PNG'),
('Tom Aluminum Roll', 'Hookah Parts', null, 3500,'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8768.PNG'),
('Al Raqi Large Aluminum Roll', 'Hookah Parts', null, 3500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8769.PNG'),
('Ice Bottle', 'Hookah Parts', null, 1000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8770.PNG'),
('Rafiea Al Bayati Cigarettes Filter', 'Hookah Parts', null, 1250, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8771.PNG'),
('Hookah Mesh Net', 'Hookah Parts', null, 3000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8754.PNG'),
('Gold Hookah Mesh Net', 'Hookah Parts', null, 3000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8755.PNG'),
('Hookah Cleaning Brush', 'Hookah Parts', null, 2000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8756.PNG'),
('Hookah Cleaning Brush', 'Hookah Parts', null, 2000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8757.PNG'),
('Gas Torch Flame Gun', 'Hookah Parts', null, 5500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8758.PNG'),
('Ice Bottle 1', 'Hookah Parts', null, 1750, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8759.PNG'),
('Small Crown Hookah Bowl Buckle', 'Hookah Parts', null, 3000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8748.PNG'),
('Hookah Tape', 'Hookah Parts', null, 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8749.PNG'),
('Finjan Net', 'Hookah Parts', null, 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8750.PNG'),
('Fdk Jumbo Aluminum Foil', 'Hookah Parts', null, 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8751.PNG'),
('Short Tongs', 'Hookah Parts', null, 1000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8752.PNG'),
('Fakher Tongs', 'Hookah Parts', null, 3000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8753.PNG'),
('Coal Heater 3', 'Hookah Parts', null, 9000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8720.PNG'),
('Ignition Gel', 'Hookah Parts', null , 3000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8721.PNG'),
('Hookah Pump', 'Hookah Parts', null, 16000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8722.PNG'),
('English Smoke Condenser', 'Hookah Parts', null, 2000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8723.PNG'),
('Gum & Mint Smoke Condenser', 'Hookah Parts', null, 2000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8724.PNG'),
('Hexa Charcoal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8725.PNG'),
('Natural Charcoal', 'Hookah Parts', '1 Kg', 5000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8726.PNG'),
('Rectangular Charcoal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8727.PNG'),
('Small Charcoal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8728.PNG'),
('Natural Cube Charcoal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8729.PNG'),
('Small Coal Stick', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8732.PNG'),
('Large Coal Stick', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8731.PNG'),
('Square Coal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8733.PNG'),
('Circular Coal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8734.PNG'),
('Fadak Square Charcoal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8735.PNG'),
('Rasafi Washer Charcoal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8736.PNG'),
('Charcoal Grill', 'Hookah Parts', null, 2000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8737.PNG'),
('Cocodice Coconut Charcoal', 'Hookah Parts', '1 Kg', 6500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8714.PNG'),
('Charcoal Igniter Cooker', 'Hookah Parts', null, 13000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8715.PNG'),
('Jamrah Natural Charcoal', 'Hookah Parts', '1 Kg', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8716.PNG'),
('Small Heater', 'Hookah Parts', null, 7000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8717.PNG'),
('Coal Heater 1', 'Hookah Parts', null, 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8718.PNG'),
('Coal Heater 2', 'Hookah Parts',null, 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8719.PNG'),
('Oxbar Strawberry Lemon Berry 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8799.jpg'),
('Oxbar Martinhoo 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8800.jpg'),
('Oxbar Purple Azberry 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8801.jpg'),
('Oxbar Blue Azberry 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8802.jpg'),
('Oxbar English 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8803.jpg'),
('Oxbar Strawberry Gum 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8804.jpg'),
('Oxbar Red Azberry 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8805.jpg'),
('Oxbar Strawberry Mango 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8806.jpg'),
('Oxbar Pink Azberry 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8807.jpg'),
('Oxbar Strawberry Lemon 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8808.jpg'),
('Oxbar Mango and Peach', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8793.jpg'),
('Oxbar Green Azberry', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8794.jpg'),
('Oxbar Strawberry Kiwi 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8795.jpg'),
('Oxbar Strawberry Banana 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8796.jpg'),
('Oxbar Watermelon Gum 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8797.jpg'),
('Oxbar Strawberry Lemon Pomegranate 2% Nicotine', 'Oxbar', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8798.jpg'),
('Oxbar G Turbo Green Azberry', 'Oxbar G Turbo', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8810.jpg'),
('Oxbar G Turbo Pink Azberry', 'Oxbar G Turbo', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8811.jpg'),
('Oxbar G Turbo Grape and Bubby Gum', 'Oxbar G Turbo', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8812.jpg'),
('Oxbar G Turbo Red Berry and Pear', 'Oxbar G Turbo', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8815.jpg'),
('Oxbar G Turbo Pineapple Coconut and Strawberry', 'Oxbar G Turbo', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8814.jpg'),
('Oxbar G Turbo Peach Mango and Pineapple', 'Oxbar G Turbo', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8817.jpg'),
('Oxbar Pod Strawberry Pomegranate and Kiwi With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8820.PNG'),
('Oxbar Pod Strawberry and Iced Watermelon With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8821.PNG'),
('Oxbar Pod Iced Strawberry and Bubby Gum With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8822.PNG'),
('Oxbar Pod Iced Watermelon and Bubby Gum With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8823.PNG'),
('Oxbar Pod Strawberry Lemon and Berry With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8824.PNG'),
('Oxbar Pod Watermelon Banana and Iced Strawberry With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8825.PNG'),
('Oxbar Pod Berry and Bubby Gum With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8826.PNG'),
('Oxbar Pod Red Wine With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8827.PNG'),
('Oxbar Pod Coffee With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8828.PNG'),
('Oxbar Pod Spearmint Ice With Battery', 'Oxbar Pod', '27000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8829.PNG'),
('Vozol Vista Dragon Fruit Banana Cherry Pod', 'Vozo;', '40000 Puffs', 16000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8831.PNG'),
('Vozol Vista Lavafire Pod', 'Vozol', '40000 Puffs', 16000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8832.PNG'),
('Oxbar Icenc Strawberry and Mango', 'Oxbar', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8834.PNG'),
('Oxbar Icenc Strawberry Lemon and Blue Berry', 'Oxbar', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8835.PNG'),
('Oxbar Icenc English', 'Oxbar', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8836.PNG'),
('Oxbar Icenc Lemon and Mix Berry', 'Oxbar', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8837.PNG'),
('Cooling Molasses Catcher', 'Hookah Parts', null, 5000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8775.PNG'),
('Bottle Hose', 'Hookah Parts', null, 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8776.PNG'),
('Khalil Mamoun Wood Hose', 'Hookah Parts', null, 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8777.PNG'),
('Steel Cooling Molasses Catcher', 'Hookah Parts', null, 5500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8778.PNG'),
('Mr. Tom Cooling Molasses Catcher', 'Hookah Parts', null, 5000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8779.PNG'),
('Raqi Jumbo Aluminum Foil', 'Hookah Parts', null, 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8780.PNG'),
('Oriental Perforated Aluminum Foil', 'Hookah Parts', null, 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8781.PNG'),
('Fadk Aluminum Foil', 'Hookah Parts', null, 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8782.PNG'),
('Al Rakey Perforated Aluminum Foil', 'Hookah Parts', null, 3000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8783.PNG'),
('Uwell Caliburn Candy Mint Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn English Bubble Gum Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn English Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn Martinho Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn Love 66 Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn Bubble Gum Mint Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn Strawberry Lemon Bubble Gum Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Caliburn G5 Pod', 'Caliburn', null, 27000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8850.PNG'),
('Uwell Caliburn Strawberry Lemon Blueberry Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Caliburn G6 Pod', 'Caliburn', null, 27000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8849.PNG'),
('Uwell Caliburn Strawberry Watermelon Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn Watermelon Bubble Gum Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn G4 Pro', 'Caliburn', null, 45000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8846.PNG'),
('Uwell Caliburn Strawberry Bubble Gum Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn Strawberry Melon Bubble Gum Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn G4 0.9Ω', 'Caliburn', null, 5500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8847.PNG'),
('Uwell Caliburn Strawberry Pina Colada Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Caliburn G4 Pod', 'Caliburn', null, 27000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8848.PNG'),
('Uwell Caliburn Watermelon Melon Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Uwell Caliburn Watermelon Ice Pod 2% Nicotine', 'Caliburn', '80000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8845.PNG'),
('Breeze Smoke Mint Pod 5% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8960.PNG'),
('Breeze Smoke Blueberry Lemon Pod 5% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8961.PNG'),
('Breeze Smoke Mixed Fruit Ice Pod 5% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8962.PNG'),
('Breeze Smoke English Ice Pod 5% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8963.PNG'),
('Breeze Smoke Strawberry Apple Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8965.PNG'),
('Breeze Smoke English Ice Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8966.PNG'),
('Breeze Smoke Blueberry Lemon Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8973.PNG'),
('Breeze Smoke Mixed Fruit Ice Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8974.PNG'),
('Breeze Smoke Strawberry Mint Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8975.PNG'),
('Breeze Smoke Mint Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8976.PNG'),
('Breeze Smoke Strawberry Watermelon Ice Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8977.PNG'),
('Breeze Smoke Pink Lemonade Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8978.PNG'),
('Breeze Smoke Miami Mint Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8979.PNG'),
('Breeze Smoke Cherry Lemon Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8980.PNG'),
('Breeze Smoke Pomegranate Berry Mint Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8981.PNG'),
('Breeze Smoke Grape Lemon Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8982.PNG'),
('Breeze Smoke Spearmint Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8983.PNG'),
('Breeze Smoke Tobacco Vanilla Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8984.PNG'),
('Breeze Smoke Lemon Mint Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8985.PNG'),
('Breeze Smoke Grape Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8986.PNG'),
('Breeze Smoke Mint Pod 5% Nicotine', 'Breeze Smoke', '2000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8987.PNG'),
('Breeze Smoke Orange Mint Pod', 'Breeze Smoke', '15000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8988.PNG'),
('Breeze Smoke Mango Pineapple Pod', 'Breeze Smoke', '15000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8989.PNG'),
('Breeze Smoke Mint Pod', 'Breeze Smoke', '15000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8990.PNG'),
('Breeze Smoke Blue Raspberry Pod', 'Breeze Smoke', '15000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8991.PNG'),
('Breeze Smoke Double Apple Pod', 'Breeze Smoke', '15000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8993.PNG'),
('Breeze Smoke Strawberry Lemon Pod', 'Breeze Smoke', '15000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8994.PNG'),
('Breeze Smoke Watermelon Mint Pod', 'Breeze Smoke', '15000 Puffs', 25000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8994.PNG'),
('Breeze Smoke Strawberry Apple 5% Nicotine Pod', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8996.PNG'),
('Breeze Smoke Strawberry Watermelon Ice 5% Nicotine Pod', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8997.PNG'),
('Breeze Smoke Grape Black Currant 5% Nicotine Pod', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8998.PNG'),
('Breeze Smoke Coconut Banana 5% Nicotine Pod', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8999.PNG'),
('Breeze Smoke Mango Twist Ice 5% Nicotine Pod', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9001.PNG'),
('Breeze Smoke Watermelon Mint 5% Nicotine Pod', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9002.PNG'),
('Breeze Smoke Cherry Cola 5% Nicotine Pod', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9003.PNG'),
('Breeze Smoke Blueberry Raspberry Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8967.PNG'),
('Breeze Smoke Raspberry Peach Ice Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8968.PNG'),
('Breeze Smoke Lemon Cola Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8969.PNG'),
('Breeze Smoke Cherry Lemon Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8970.PNG'),
('Breeze Smoke Raspberry Lemon Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8970.PNG'),
('Breeze Smoke Peach Berry Pod 3% Nicotine', 'Breeze Smoke', '6000 Puffs', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_8972.PNG'),
('Joy Dtl VIP Pod', 'Joy', '40000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9005.PNG'),
('Joy Lemon Mint Pod', 'Joy', '40000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9006.PNG'),
('Joy Love 66 Pod', 'Joy', '40000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9007.PNG'),
('Joy Blueberry Pod', 'Joy', '40000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9008.PNG'),
('Joy Blueberry & Strawberry Pod', 'Joy', '40000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9009.PNG'),
('Joy Coffee Pod 2% Nicotine', 'Joy', '40000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9010.PNG'),
('Oxbar Svopp Battery', 'Oxbar Svoop',null, 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9024.PNG'),
('Oxbar Svopp Watermelon Melon Strawberry Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9025.PNG'),
('Oxbar Svopp Red Azberry Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9026.PNG'),
('Oxbar Svopp Lemon Cake Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9027.PNG'),
('Oxbar Svopp Red Wine Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9028.PNG'),
('Oxbar Svopp Banana Cake Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9029.PNG'),

('Oxbar Svopp Strawberry Kiwi Pomegranate Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9036.PNG'),
('Oxbar Svopp Watermelon Melon Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9037.PNG'),
('Oxbar Svopp Purple Azberry Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9038.PNG'),
('Oxbar Svopp Watermelon Bubble Gum Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9039.PNG'),
('Oxbar Svopp Apricot Watermelon Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9040.PNG'),
('Oxbar Svopp Strawberry Kiwi Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9040.PNG'),

('Oxbar Svopp Strawberry Watermelon Bubble Gum Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9042.PNG'),
('Oxbar Svopp Strawberry Bubble Gum Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9043.PNG'),
('Oxbar Svopp Strawberry Lemon Berry Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9044.PNG'),
('Oxbar Svopp Spearmint Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9045.PNG'),
('Oxbar Svopp Cosmo Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9046.PNG'),
('Oxbar Svopp Bubble Gum Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9047.PNG'),

('Oxbar Svopp Berry Pear Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9048.PNG'),
('Oxbar Svopp Pink Azberry Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9049.PNG'),
('Oxbar Svopp Blue Azberry Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9050.PNG'),
('Oxbar Svopp Strawberry Melon Bubble Gum Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9051.PNG'),
('Oxbar Svopp Peach Blueberry Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9052.PNG'),
('Oxbar Svopp Strawberry Kiwi Banana Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9053.PNG'),

('Oxbar Svopp Green Azberry Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9054.PNG'),
('Oxbar Svoop Bobby Banana Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9055.PNG'),
('Oxbar Svoop Bobby Grape Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9056.PNG'),
('Oxbar Svoop Bobby Strawberry Honeydew Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9057.PNG'),
('Oxbar Svoop Bobby Mint Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9058.PNG'),
('Oxbar Svoop Bobby Blue Raspberry Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9059.PNG'),

('Oxbar Svoop Bobby Strawberry Watermelon Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9060.PNG'),
('Oxbar Svoop Bobby Berry Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9060.PNG'),
('Oxbar Svoop Bobby Watermelon Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9062.PNG'),
('Oxbar Svoop Bobby Peach Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9063.PNG'),
('Oxbar Svoop Bobby Pomegranate Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9328.PNG'),

('Oxbar Svopp Peach Apricot Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9030.PNG'),
('Oxbar Svopp Strawberry Watermelon Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9031.PNG'),
('Oxbar Svopp Berry Bubble Gum Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9032.PNG'),
('Oxbar Svopp Black English Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9033.PNG'),
('Oxbar Svopp Banana Strawberry Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9034.PNG'),
('Oxbar Svopp Martinho Ice Pod', 'Oxbar Svoop', '27000 Puffs', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9035.PNG'),
('Lost Mary Kiwi Passion Fruit Guava Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9072.PNG'),
('Lost Mary Miami Mint Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9074.PNG'),
('Lost Mary Strawberry Ice Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9075.PNG'),
('Lost Mary Vanilla Cream Tobacco Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9076.PNG'),
('Lost Mary Black Grape Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9077.PNG'),

('Lost Mary Desert Oasis Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9067.PNG'),
('Lost Mary Peach Mango Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9068.PNG'),
('Lost Mary Blueberry Ice Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9069.PNG'),
('Lost Mary Strawberry Kiwi Ice Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9070.PNG'),
('Lost Mary Mango Peach Melon Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9071.PNG'),
('Lost Mary Bubble Gum Melon Pod', 'Lost Mary', '35000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9072.PNG'),
('Huuca Strawberry Ice Cream Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9086.PNG'),
('Huuca Grape Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9087.PNG'),
('Huuca Cherry Cola Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9088.PNG'),
('Huuca Mixed Berry Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9089.PNG'),
('Huuca Strawberry Kiwi Pod', 'Huuca', '80000 Puffs', 19000, ''),
('Huuca Banana Melon Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9081.PNG'),
('Huuca Mango Peach Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9082.PNG'),
('Huuca English Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9083.PNG'),
('Huuca Strawberry Peach Pomegranate Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9084.PNG'),
('Huuca Watermelon Ice Pod', 'Huuca', '80000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9085.PNG'),
('Cool Star Pink Colada Pod', 'Cool Star', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9094.PNG'),
('Cool Star Pink Panther Ice Pod', 'Cool Star', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9095.PNG'),
('Cool Star Azbri Pod', 'Cool Star', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9096.PNG'),
('Cool Star Candy Panther Ice Pod', 'Cool Star', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9097.PNG'),
('Cool Star Gum Mint Pod', 'Cool Star', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9098.PNG'),
('Cool Star Cosmo Ice Pod', 'Cool Star', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9099.PNG'),
('Cool Star Panther Gum Ice Pod', 'Cool Star', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9100.PNG'),
('IQOS Iluma I', 'IQOS', '', 125000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9091.PNG'),
('Tesla Bar Babylon English Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9111.PNG'),
('Tesla Bar Babylon Arrow Gum Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9112.PNG'),
('Tesla Bar Babylon Tropical Fruits Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9113.PNG'),
('Tesla Bar Babylon Peach Juice Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9114.PNG'),
('Tesla Bar Juicy Peach Ice Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9115.PNG'),
('Tesla Bar Watermelon Ice Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9116.PNG'),
('Tesla Bar Babylon Watermelon Ice Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9105.PNG'),
('Tesla Bar Babylon Berry Watermelon Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9106.PNG'),
('Tesla Bar Babylon Strawberry Kiwi Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9107.PNG'),
('Tesla Bar Babylon Pomegranate Strawberry Bubble Gum Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9108.PNG'),
('Tesla Bar Babylon Strawberry Mojito Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9109.PNG'),
('Tesla Bar Babylon Peach Mango Watermelon Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9110.PNG'),
('Tesla Bar Miami Mint Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9122.PNG'),
('Tesla Bar Tropical Rambo Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9124.PNG'),
('Tesla Bar Strawberry Kiwi Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9117.PNG'),
('Tesla Bar Mojito Strawberry Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9118.PNG'),
('Tesla Bar Peach Mango Watermelon Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9119.PNG'),
('Tesla Bar Pomegranate Strawberry Bubble Gum Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9120.PNG'),
('Tesla Bar English Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9121.PNG'),
('Tesla Bar Blueberry Watermelon Pod', 'Tesla Bar', '60000 Puffs', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9122.PNG'),
('Vozol Gear Hookah Watermelon Bubble Gum Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9133.PNG'),
('Vozol Gear Hookah Strawberry Margarita Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9135.PNG'),
('Vozol Gear Hookah Strawberry Bubble Gum Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9136.PNG'),
('Vozol Gear Hookah Watermelon Ice Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9137.PNG'),
('Vozol Gear Hookah Strawberry Watermelon Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9138.PNG'),
('Vozol Gear Hookah Martinho Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9139.PNG'),
('Vozol Gear Hookah Mojito Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9127.PNG'),
('Vozol Gear Hookah Cherry Cola Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9128.PNG'),
('Vozol Gear Hookah Strawberry Kiwi Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9129.PNG'),
('Vozol Gear Hookah Strawberry Mango Peach Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9131.PNG'),
('Vozol Gear Hookah Gum Mint Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9132.PNG'),
('Vozol Gear Hookah Love 777 Pod', 'Vozol Gear Hookah', '40000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9133.PNG'),
('Oxbar Al-Sheikh Gum Mint Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9148.PNG'),
('Oxbar Al-Sheikh Grape Bubble Gum Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9150.PNG'),
('Oxbar Al-Sheikh Cosmo Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9151.PNG'),
('Oxbar Al-Sheikh Strawberry Bubble Gum Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9152.PNG'),
('Oxbar Al-Sheikh Love 66 Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9153.PNG'),
('Oxbar Al-Sheikh Pomegranate Berry Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9154.PNG'),
('Oxbar Al-Sheikh Watermelon Bubble Gum Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9155.PNG'),
('Oxbar Al-Sheikh Strawberry Lemon Bubble Gum Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9156.PNG'),
('Oxbar Al-Sheikh Spearmint Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9157.PNG'),
('Oxbar Al-Sheikh Banana Peach Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9158.PNG'),
('Oxbar Al-Sheikh Cherry Cola Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9143.PNG'),
('Oxbar Al-Sheikh Strawberry Watermelon Bubble Gum Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9144.PNG'),
('Oxbar Al-Sheikh English Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9145.PNG'),
('Oxbar Al-Sheikh Martinho Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9146.PNG'),
('Oxbar Al-Sheikh Red Wine Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9147.PNG'),
('Oxbar Al-Sheikh Strawberry Watermelon Melon Pod', 'Oxbar Al-Sheikh', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9148.PNG'),
('IGet Tobacco Pod', 'IGet', '5500 Puffs', 7000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9160.PNG'),
('IGet Mango Ice Pod', 'IGet', '5500 Puffs', 7000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9161.PNG'),
('IGet Orange Soda Pod', 'IGet', '5500 Puffs', 7000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9162.PNG'),
('IGet Sour Lemon Pod', 'IGet', '5500 Puffs', 7000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9163.PNG'),
('IGet Berry Grape Pod', 'IGet', '5500 Puffs', 7000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9164.PNG'),
('Crown Bar Al Fakher Mixed Berry Pod', 'Al Fakher', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9175.PNG'),
('Crown Bar Al Fakher Mega Max Berry Blue Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9176.PNG'),
('Crown Bar Al Fakher Mega Max Gum Mint Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9177.PNG'),
('Crown Bar Al Fakher Mega Max Strawberry Cherry Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9178.PNG'),
('Crown Bar Al Fakher Mega Max Mango Pineapple Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9179.PNG'),
('Crown Bar Al Fakher Mega Max Mixed Berry Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9180.PNG'),
('Crown Bar Al Fakher Mega Max Lemon Mint Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9181.PNG'),
('Crown Bar Al Fakher Mega Max Blueberry Cherry Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9182.PNG'),
('Crown Bar Al Fakher Mega Max Orange Mint Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9183.PNG'),
('Crown Bar Al Fakher Mega Max Watermelon Cherry Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9184.PNG'),
('Crown Bar Al Fakher Mega Max Blueberry Gum Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9185.PNG'),
('Crown Bar Al Fakher Mega Max Two Apple Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9186.PNG'),
('Crowb Bar Al Fakher Blueberry Sour Raspberry Pod', 'Al Fakher', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9169.PNG'),
('Crowb Bar Al Fakher Blueberry Cherry Pod', 'Al Fakher', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9170.PNG'),
('Crowb Bar Al Fakher Strawberry Cherry Pod', 'Al Fakher', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9170.PNG'),
('Crowb Bar Al Fakher Mango Pineapple Pod', 'Al Fakher', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9170.PNG'),
('Crowb Bar Al Fakher Strawberry Punch Pod', 'Al Fakher', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9173.PNG'),
('Crowb Bar Al Fakher Peach Ice Pod', 'Al Fakher', '60000 Puffs', 21000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9174.PNG'),
('Crown Bar Al Fakher Mega Max Blueberry & Raspberry Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9187.PNG'),
('Crown Bar Al Fakher Mega Max Watermelon Pineapple Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9188.PNG'),
('Crown Bar Al Fakher Mega Max Engleezi Pod', 'Al Fakher', '40000 Puffs', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9189.PNG'),
insert into public.products (product_name, category, weight, price, image)
values
('Mosmo Cherry & Cola Pod', 'Mosmo Storm x', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9191.PNG'),
('Mosmo Strawberry & Banana Pod', 'Mosmo Storm x', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9192.PNG'),
('Mosmo Mango With Peach & Watermelon Pod', 'Mosmo Storm x', '30000 Puffs', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9325.PNG'),

('Mosmo Sultan Mango Ice Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9203.PNG'),
('Mosmo Sultan Mixed Fruits Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9204.PNG'),
('Mosmo Sultan Watermelon & Lemon Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9205.PNG'),
('Mosmo Sultan Strawberry Watermelon Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9206.PNG'),
('Mosmo Sultan Grape Mint Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9207.PNG'),
('Mosmo Sultan Strawberry Kiwi Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9208.PNG'),
('Mosmo Sultan Strawberry Bubble Gum Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9209.PNG'),
('Mosmo Sultan Gum Mint Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9210.PNG'),
('Mosmo Sultan Martinho Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9211.PNG'),
('Mosmo Sultan Watermelon Bubble Gum Pod', 'Mosmo Sultan', '50000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9212.PNG'),
('Mosmo Sultan Lemon Mint Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9213.PNG'),
('Mosmo Sultan Berries Ice Pod', 'Mosmo Sultan', '50000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9214.PNG'),
('Mosmo Sultan Peach, Mango & Watermelon Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9197.PNG'),
('Mosmo Sultan Peach Ice Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9198.PNG'),
('Mosmo Sultan Strawberry & Lemon Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9199.PNG'),
('Mosmo Sultan Love 66 Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9200.PNG'),
('Mosmo Sultan Banana & Melon Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9201.PNG'),
('Mosmo Sultan Mixed Berries Pod', 'Mosmo Sultan', '50000 Puffs', 18000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9202.PNG'),
('Uno Playing Cards', 'Cards', null , 2500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9222.PNG'),
('Nexlim', 'Nexlim', null , 50000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9226.PNG'),

('Mosmo GT Strawberry and Bubby Gum', 'Mosmo GT', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9216.PNG'),
('Mosmo GT Strawberry and Kiwi', 'Mosmo GT', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9217.PNG'),
('Mosmo GT Martino', 'Mosmo GT', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9218.PNG'),
('Mozmo Gt Gum & Mint', 'Mosmo GT', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9219.PNG'),
('Mozmo Gt Blueberry & Raspberry', 'Mosmo GT', '40000 Puffs', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9220.PNG'),

('Oxbar Watermelon Bubblegum Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9239.PNG'),
('Oxbar Pomegranate Blueberry Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9240.PNG'),
('Uwell Pomegranate Bubble Gum Juice 2% Nicotine', 'Juices', '30 Ml', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9234.PNG'),
('Uwell Strawberry Kiwi Juice 2% Nicotine', 'Juices', '30 Ml', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9235.PNG'),
('Uwell Double Apple Juice 2% Nicotine', 'Juices', '30 Ml', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9236.PNG'),
('Uwell Candy Mint Juice 2% Nicotine', 'Juices', '30 Ml', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9237.PNG'),
('Uwell Cool Mint Juice 2% Nicotine', 'Juices', '30 Ml', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9238.PNG'),
('Oxbar Coffee Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9245.PNG'),
('Uwell Strawberry Juice 2% Nicotine', 'Juices', '30 Ml', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9246.PNG'),
('Oxbar Red Wine Juice', 'Juices', '100 Ml', 19000, ''),
('Oxbar Strawberry Kiwi Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9247.PNG'),
('Oxbar Strawberry Banana Melon Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9242.PNG'),
('Oxbar Strawberry Kiwi Pomegranate Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9243.PNG'),
('Oxbar Strawberry Kiwi Watermelon Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9244.PNG'),
('Oxbar Strawberry Watermelon Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9252.PNG'),
('Oxbar Pineapple Passion Fruit Lychee Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9253.PNG'),
('Oxbar Honeydew Bubble Gum Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9254.PNG'),
('Oxbar English Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9255.PNG'),
('Oxbar Apricot Peach Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9256.PNG'),
('Oxbar Apricot Watermelon Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9257.PNG'),
('Oxbar Spearmint Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9258.PNG'),
('Oxbar Gum Mint Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9258.PNG'),
('Oxbar Peach Pear Candy Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9260.PNG'),
('Oxbar Strawberry Bubble Gum Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9248.PNG'),
('Oxbar Strawberry Raspberry Watermelon Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9249.PNG'),
('Oxbar Strawberry Watermelon Bubble Gum Juice', 'Juices', '100 Ml', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9251.PNG'),
('Uwell Strawberry Lemonade Juice 2% Nicotine', 'Juices', '30 Ml', 14000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9250.PNG'),

('Xlime Pro Red', 'Xlime Vapes', '', 45000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9263.PNG'),
('Xlime Pro Silver', 'Xlime Vapes', '', 45000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9264.PNG'),
('Xlime Pro Carbon Fiber', 'Xlime Vapes', '', 45000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9265.PNG'),
('Oxva Xlim Go2', 'Xlime Vapes', '', 32000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9266.PNG'),
('Oxva Xlim Go2', 'Xlime Vapes', '', 32000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9267.PNG'),
('Oxva Xlim Go2', 'Xlime Vapes', '', 32000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9268.PNG'),
('Caliburn G7 Caterge 0.9', 'Cartridge', '3 Ml', 5500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9273.PNG'),
('OXVA XLIM Cartridges 0.4Ω', 'Cartridge', '3 Ml', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9274.PNG'),
('OXVA XLIM Cartridges 0.6Ω', 'Cartridge', '3 Ml', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9275.PNG'),
('OXVA XLIM Cartridges 0.8Ω', 'Cartridge', '3 Ml', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9276.PNG'),
('OXVA XLIM SQ Pro 2 Device', 'Xlime Vapes', '', 50000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9269.PNG'),
('Fasoul Q1 Pro Black Device', 'Xlime Vapes', '', 40000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9270.PNG'),
('Fasoul C2 Blue Device', 'Xlime Vapes', '', 55000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9271.PNG'),

('Terea Tobacco Amber', 'Cigarettes', '', 3500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9280.PNG'),
('Terea Tobacco Sun Pearl Menthol', 'Cigarettes', '', 3500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9281.PNG'),
('Terea Tobacco Purple Wave Menthol', 'Cigarettes', '', 3500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9282.PNG'),
('Terea Tobacco Turquoise Menthol', 'Cigarettes', '', 3500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9283.PNG'),
('Terea Tobacco Silver', 'Cigarettes', '', 3500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9284.PNG'),
('Terea Tobacco Sienna', 'Cigarettes', '', 3500, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9285.PNG'),

('Nuso Purple Cigarette', 'Cigarettes', '', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9292.PNG'),
('Nuso Blue Cigarette', 'Cigarettes', '', 19000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9293.PNG'),

('Terea Arabic Tobacco Amber', 'Cigarettes', '', 33000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9286.PNG'),
('Terea Arabic Tobacco Sun Pearl Menthol', 'Cigarettes', '', 33000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9287.PNG'),
('Terea Arabic Tobacco Purple Wave Menthol', 'Cigarettes', '', 33000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9288.PNG'),
('Terea Arabic Tobacco Turquoise Menthol', 'Cigarettes', '', 33000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9289.PNG'),
('Terea Arabic Tobacco Silver', 'Cigarettes', '', 33000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9290.PNG'),
('Terea Arabic Tobacco Sienna', 'Cigarettes', '', 33000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9291.PNG'),

('Velo Tropical Mango Snuz', 'Velo', '', 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9302.PNG'),
('Velo Bright Peppermint Snuz', 'Velo', '', 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9296.PNG'),
('Velo Blue Raspberry Snuz', 'Velo', '', 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9297.PNG'),
('Velo Purple Grape Snuz', 'Velo', '', 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9298.PNG'),
('Velo Ice Cherry Snuz', 'Velo', '', 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9299.PNG'),
('Velo Peppermint Storm Snuz', 'Velo', '', 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9300.PNG'),
('Velo Ruby Berry Snuz', 'Velo', '', 12000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9301.PNG'),

('Original Card Games', 'Cards', '', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9312.PNG'),
('American Card Games', 'Cards', '', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9313.PNG'),
('Girls Card Games', 'Cards', '', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9314.PNG'),
('Kull Card Games', 'Cards', '', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9315.PNG'),
('Refraction Card Games', 'Cards', '', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9316.PNG'),
('Disobedience Card Games', 'Cards', '', 17000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9317.PNG'),
('Bicycle Card Games', 'Cards', '', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9318.PNG'),
('Emerald Card Games', 'Cards', '', 15000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9319.PNG'),
('Joker Playing Cards', 'Cards', '', 6000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9320.PNG'),
('Nap Card Games', 'Cards', '', 4000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9321.PNG'),
('Backgammon', 'Backgammon', '', 20000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9323.PNG'),
('Leather Wrapped Backgammon Table', 'Backgammon', '', 23000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9324.PNG'),
('Original Domino', 'Dominos', '', 9000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9305.PNG'),
('Regular Domino', 'Dominos', '', 5000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9305.PNG'),
('Plastic Box Domino', 'Dominos', '', 4000, 'https://vowybopgplzakkznsuhq.supabase.co/storage/v1/object/public/products/IMG_9306.PNG');